{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agari-frontend.fullname" . }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- $root := . }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "agari-frontend.fullname" $root }}
                port:
                  number: {{ $.Values.service.port }}
            {{- end }}
      {{- end }}
  {{- if .Values.ingress.tls }}
    tls: {{ toYaml .Values.ingress.tls | nindent 2 }}
  {{- end }}
{{- end -}}